### ISSUE TITLE
ブラウザによるフォントの揺れ

### ISSUE THREAD

**Issue by zuckeyM-17** [zuckeyM-17/shiganai-radio-page#37]
<img width="511" alt="2017-08-05 14 26 53" src="https://user-images.githubusercontent.com/20605685/28993149-299ac0ec-79ea-11e7-90ca-699f3c0b4a21.png">

**Comment by jumtech** [comment]
## Noto Sans（源ノ角ゴシック）
http://qiita.com/shotets/items/502f8093d53369eaab50#noto-sans%E6%BA%90%E3%83%8E%E8%A7%92%E3%82%B4%E3%82%B7%E3%83%83%E3%82%AF
- プレーンな印象
- 英数が縦長

<img width="812" alt="2017-08-05 14 50 48" src="https://user-images.githubusercontent.com/20605685/28993267-82ae09b6-79ed-11e7-90e9-3cdbf3f08044.png">

## Mplus 1p
http://qiita.com/shotets/items/502f8093d53369eaab50#mplus-1p
- 楽しげ

<img width="803" alt="2017-08-05 14 53 10" src="https://user-images.githubusercontent.com/20605685/28993289-d5d4bfb8-79ed-11e7-8b4a-fc2c0d146860.png">

## Rounded Mplus 1c
http://qiita.com/shotets/items/502f8093d53369eaab50#rounded-mplus-1c
- 違いがわからん

<img width="798" alt="2017-08-05 15 03 29" src="https://user-images.githubusercontent.com/20605685/28993347-45f5f63a-79ef-11e7-8da1-e768397ffeaa.png">

**Comment by jumtech** [comment]
- google web fontsだと、@importするだけで色々とやってくれるらしい.
- @font-faceは宣言しなくて良さげ.
- 楽しげなので`Mplus 1p`にした

```css
@import url(https://fonts.googleapis.com/earlyaccess/mplus1p.css);
...
body {
  margin: 0;
  font-size: .14em;
  font-family: 'Mplus 1p', sans-serif;
  font-weight: 400;
  }
```
